In [ ]:
# Numpy

In [1]:
import numpy as np
import time 


def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 5.1222 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 3152.1828 ms 


## Creation

You can create arrays in different ways
- from List
- from zero
- from a range
- from random

In [16]:
import numpy as np

arr = np.array([4, 1, 2, 3])
print(f"Array of list (4) as : {arr}")

arr = np.zeros((4))
print(f"Array of list (4) as : {arr}")

arr = np.arange(1, 10, 2)
print(f"Array of range (4) as : {arr}")

Array of list (4) as : [4 1 2 3]
Array of list (4) as : [0. 0. 0. 0.]
Array of range (4) as : [1 3 5 7 9]


## Zeros

Helps to create and array of Zeros using shape function

In [12]:
import numpy as np

arr = np.zeros(4)
print(f"Array of zeros (4) as : {arr}")

arr = np.zeros((4, ))
print(f"Array of zeros (4, ) as : {arr}")

arr = np.zeros((1, 4))
print(f"Array of zeros (1, 4) as : {arr}")

arr = np.zeros((5,), dtype=int)
print(f"Array of zeros (5, ) of int as : {arr}")

arr = np.zeros((4, 1))
print(f"Array of zeros (4, 1) as : {arr}")

arr = np.zeros((4, 2))
print(f"Array of zeros (4, 2) as : {arr}")


Array of zeros (4) as : [0. 0. 0. 0.]
Array of zeros (4, ) as : [0. 0. 0. 0.]
Array of zeros (1, 4) as : [[0. 0. 0. 0.]]
Array of zeros (5, ) of int as : [0 0 0 0 0]
Array of zeros (4, 1) as : [[0.]
 [0.]
 [0.]
 [0.]]
Array of zeros (4, 2) as : [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [23]:
## Reshape
import numpy as np

org = np.arange(0, 1000)
print(f"Array of range (100) as : {org.shape}")
arr = org.reshape((50, 20))
print(f"Array of range (100) as : {arr.shape}")
arr = org.reshape((4, 250))
print(f"Array of range (100) as : {arr.shape}")
print(arr[0, 1])
print(arr[0])
print(arr[0]/255)


Array of range (100) as : (1000,)
Array of range (100) as : (50, 20)
Array of range (100) as : (4, 250)
1
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 2

## Operations

Arrays are like other datatypes and according to their mathematical difinition, they should support the following operations
- Addition (Two Arrays, Scalars)
- Subtract (Two Arrays, Scalars)
- Multiplication (Two Arrays, Scalars)
- Division (Two Arrays, Scalars)
- Power (Two Arrays, Scalars)


In [31]:
arr1 = np.arange(0, 20, 2)
arr2 = np.arange(1, 20, 2)
print(arr1)
print(arr2)
print(arr1 + 10) #scalar
print(arr1 - 10) #scalar
print(arr1 * 10) #scalar
print(arr1 / 10) #scalar
print(arr1 + arr2) # adding arrays
print(arr1 * arr2) # multiplying arrays
print(arr1 / arr2) # dividing arrays
print(arr1 ** 2) # multiplying arrays

[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[10 12 14 16 18 20 22 24 26 28]
[-10  -8  -6  -4  -2   0   2   4   6   8]
[  0  20  40  60  80 100 120 140 160 180]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[ 1  5  9 13 17 21 25 29 33 37]
[  0   6  20  42  72 110 156 210 272 342]
[0.         0.66666667 0.8        0.85714286 0.88888889 0.90909091
 0.92307692 0.93333333 0.94117647 0.94736842]
[  0   4  16  36  64 100 144 196 256 324]


## Matrix


In [39]:
arr1 = np.arange(0, 20)
arr2 = np.arange(20, 40)
print(arr1)
print(arr2)

arr3 = arr1.dot(arr2) # 1*1 #Sum(i * j)
print(f"result (  1 *  1 ) : {arr3}") 

arr2_t = arr2.reshape((20, 1))
arr3 = arr1.dot(arr2_t) # 1*1 : Matrix
print(arr1)
print(arr2)
print(f"result (  1 *  1 ) : {arr3}") 

arr1 = arr1.reshape((4, 5))
arr2 = arr2.reshape((5, 4))

print(arr1)
print(arr2)
print(f"result (  4 *  4 ) : {arr1.dot(arr2)}") 


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
result (  1 *  1 ) : 6270
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
result (  1 *  1 ) : [6270]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
result (  4 *  4 ) : [[ 320  330  340  350]
 [1020 1055 1090 1125]
 [1720 1780 1840 1900]
 [2420 2505 2590 2675]]


In [35]:
arr1 = arr1.reshape((4, 5))
arr2 = arr2.reshape((5, 4))
arr3 = arr1.dot(arr2) # 4*4

print(arr1)
print(arr2)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
6270
